---
output: stevetemplates::cv
geometry: margin=1in

title: "CV"
author: Benjamin Mirin

jobtitle: "Ph.D. Candidate | Cornell University"
address: "Cornell Lab of Ornithology · Ithaca · New York 14850, USA"
fontawesome: yes
email: bhm48@cornell.edu
# github: svmiller
# twitter: stevenvmiller
#osf: "Enter 5 digit osf string here"
phone: "+1 978 509 5404"
web: benmirin.com
updated: TRUE
rdateformat: "`r format(Sys.time(), '%d %b %Y')`"

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Work Experience

**Explorer** \hfill National Geographic Society \hfill **2016-Present**

*Project 4: Explorer Mindset, 2019 (Team member)*

*Project 3: Grandpa’s Reef, 2018 (Team member)*

*Project 2: Remixing Madagascar, 2016 (Principle Investigator)*

*Project 1: Sky Island Beatbox, 2015 (Team member)*

**Science Communicator** \hfill New York, NY \hfill **2014-Present**

**Senior Fellow** \hfill Safina Center at Stony Brook University \hfill **2016-2020**

**Inaugural Artist In Residence** \hfill Wildlife Conservation Society \hfill **2016**

**Web Producer** \hfill Slate Magazine \hfill **2013-2015**

**Ambassador** \hfill Nanae Town Government, Hokkaido, Japan \hfill **2010-2012**

# Education

*New College, Oxford University*, B.A. Chemistry \hfill 1899

#Education
*   Ph.D. Candidate, Cornell University **2019-2024**
*   B.A., Carleton College **2006-2010**

# Publications

## Journal Articles

Student. 1938. "Comparison between Balanced and Random Arrangements on Field Plots." *Biometrika* 29(3-4): 363--378.

Student. 1936. "Co-operation in Large Scale Experiments." *Supplement to Journal of the Royal Statistical Society* 3(2): 115--136.

Student. 1931. "On the *z* Test." *Biometrika* 23(3-4): 407-408.

Student. 1931. "The Lanarkshire Milk Experiment." *Biometrika* 23(3-4): 398--406.

Student. 1929. "Statistics in Biological Research." *Nature* 124: 93

Student. 1927. "Errors of Routine Analysis." *Biometrika* 19(1-2): 151--164.

Student. 1926. "Mathematics and Agronomy." *Journal of the American Society of Agronomy* 18.

Student. 1925. "New Tables for Testing the Significance of Observations." *Metron* 5(3): 105--108.

Student. 1923. "On Testing Varieties of Cereals." *Biometrika* 15(3-4): 271--293.

Student. 1921. "An Experimental Determination of the Probable Error of Dr. Spearman's Correlation Co-efficient" *Biometrika* 13(2-3): 263--282.

Student. 1917. "Tables for Estimating the Probability That the Given Mean of a Unique Sample of Observations Lies between $-\infty$ and Any Given Distance of the Mean of the Population from Which the Sample Is Drawn." *Biometrika* 11(4): 414--417.

Student. 1909. "The Distribution of the Means of Samples Which Are Not Drawn at Random." *Biometrika* 7(1-2): 210--214.

Student. 1908. "Probable Error of a Correlation Coefficient." *Biometrika* 6(2-3): 302--310.

Student. 1908. "The Probable Error of a Mean." *Biometrika* 6(1): 1--25.

Student. 1907. "On the Error of Counting with a Haemacytometer." *Biometrika* 5(3): 351--360.

## Other Publications

Student. 1905. "The Pearson Co-efficient of Correlation." Supplement to Report of 1904, Arthur Guinness Son & Company.

Student. 1904. "The Application of the 'Law of Error' to the Work of the Brewery." Report, Arthur Guinness Son & Company.

# References

Available upon request, though likely would include Holger Klinck and Marissa Garcia. Please send corrections, feedback, or details of missed publications (of which there are probably a few) to Holger.Klinck@cornell.edu and mg2377@cornell.edu. 
